
package edu.ub.prog2.PrietoDehghanPourAstor.vista;

import edu.ub.prog2.PrietoDehghanPourAstor.controlador.*;
import edu.ub.prog2.PrietoDehghanPourAstor.model.*;
import edu.ub.prog2.utils.FitxerAudioErrorException;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 * Clase ReproductorUB4 que conte tot el disseny de la interficie grafica.
 * @author Astor Prieto
 */
public class ReproductorUB4 extends javax.swing.JFrame {
    
    CtrlReproductor control;
    FitxerAudio f;
    LlistaReproduccio lr;
    

    /**
     * Constructor del objecte ReproductorUB4.
     */
    public ReproductorUB4() {
        initComponents();
        control = new CtrlReproductor();
        f = new FitxerAudio("");
        lr = new LlistaReproduccio("");
        
        omplirBiblioteca();
        omplirLlistes();
    }

    /**
     * Metode per a omplir les llistes de la Biblioteca.
     */
    public void omplirBiblioteca() {
        try {
            ArrayList llista = control.getBiblioteca().getBiblioteca();
            DefaultListModel model = new DefaultListModel();
            model.clear();
        
            for (Object item: llista) {
                model.addElement(item);
            }
            listBiblioteca.setModel(model);
            listPistesBiblioteca.setModel(model);
            
        } catch (CloneNotSupportedException ex) {
            System.err.println(ex.getMessage());
        }
    }
    
    /**
     * Metode per a omplir el ComboBox amb les llistes de reproduccio.
     */
    public void omplirLlistes() {
        String [] llista = control.getLlistesReproduccio();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        for (Object item: llista) {
            model.addElement(item);
        }
        comboBoxLlistes.setModel(model);
    }
    
    /**
     * Metode per a omplir la llista amb les pistes de la llista seleccionada al ComboBox.
     * @param lst (Nom de la Llista) 
     */
    public void omplirPistesLlista(String lst) {
        ArrayList llista = control.getLlistaReproduccio(lst).getBiblioteca();
        DefaultListModel model = new DefaultListModel();
        model.clear();
        
        for (Object item: llista) {
            model.addElement(item);
        }
        listLlistaReproduccio.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanelMenu = new javax.swing.JTabbedPane();
        panelBiblioteca = new javax.swing.JPanel();
        btnAfegirFitxer = new javax.swing.JButton();
        btnEliminarFitxer = new javax.swing.JButton();
        btnReproduirBiblio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBiblioteca = new javax.swing.JList();
        btnGuardarDades = new javax.swing.JButton();
        btnRecuperarDades = new javax.swing.JButton();
        panelReproduccio = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listLlistaReproduccio = new javax.swing.JList();
        btnCrearLlista = new javax.swing.JButton();
        btnEliminarLlista = new javax.swing.JButton();
        btnAfegirPistaLlista = new javax.swing.JButton();
        btnEliminarPistaLlista = new javax.swing.JButton();
        comboBoxLlistes = new javax.swing.JComboBox();
        btnReproduirLlista = new javax.swing.JButton();
        btnReproduirSelecc = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listPistesBiblioteca = new javax.swing.JList();
        panelControl = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        chkCiclic = new javax.swing.JCheckBox();
        chkAleatori = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAfegirFitxer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconNew.png"))); // NOI18N
        btnAfegirFitxer.setText("Afegir Fitxer");
        btnAfegirFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirFitxerActionPerformed(evt);
            }
        });

        btnEliminarFitxer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconLess.png"))); // NOI18N
        btnEliminarFitxer.setText("Eliminar Fitxer");
        btnEliminarFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFitxerActionPerformed(evt);
            }
        });

        btnReproduirBiblio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconPlay.png"))); // NOI18N
        btnReproduirBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproduirBiblioActionPerformed(evt);
            }
        });

        listBiblioteca.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listBiblioteca);

        btnGuardarDades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconSave.png"))); // NOI18N
        btnGuardarDades.setText("Guardar Biblioteca");
        btnGuardarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDadesActionPerformed(evt);
            }
        });

        btnRecuperarDades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconLoad.png"))); // NOI18N
        btnRecuperarDades.setText("Recuperar Biblioteca");
        btnRecuperarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarDadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBibliotecaLayout = new javax.swing.GroupLayout(panelBiblioteca);
        panelBiblioteca.setLayout(panelBibliotecaLayout);
        panelBibliotecaLayout.setHorizontalGroup(
            panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelBibliotecaLayout.createSequentialGroup()
                        .addGap(0, 259, Short.MAX_VALUE)
                        .addComponent(btnGuardarDades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecuperarDades))
                    .addGroup(panelBibliotecaLayout.createSequentialGroup()
                        .addComponent(btnAfegirFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarFitxer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReproduirBiblio)))
                .addContainerGap())
        );
        panelBibliotecaLayout.setVerticalGroup(
            panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAfegirFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReproduirBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarDades, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecuperarDades, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPanelMenu.addTab("Biblioteca Musical", panelBiblioteca);

        listLlistaReproduccio.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listLlistaReproduccio);

        btnCrearLlista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconPlus.png"))); // NOI18N
        btnCrearLlista.setText("Crear Llista");
        btnCrearLlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearLlistaActionPerformed(evt);
            }
        });

        btnEliminarLlista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconMinus.png"))); // NOI18N
        btnEliminarLlista.setText("Eliminar Llista");
        btnEliminarLlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLlistaActionPerformed(evt);
            }
        });

        btnAfegirPistaLlista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconNew.png"))); // NOI18N
        btnAfegirPistaLlista.setToolTipText("");
        btnAfegirPistaLlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirPistaLlistaActionPerformed(evt);
            }
        });

        btnEliminarPistaLlista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconLess.png"))); // NOI18N
        btnEliminarPistaLlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPistaLlistaActionPerformed(evt);
            }
        });

        comboBoxLlistes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxLlistes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLlistesActionPerformed(evt);
            }
        });

        btnReproduirLlista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconNext.png"))); // NOI18N
        btnReproduirLlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproduirLlistaActionPerformed(evt);
            }
        });

        btnReproduirSelecc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconPlay.png"))); // NOI18N
        btnReproduirSelecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproduirSeleccActionPerformed(evt);
            }
        });

        listPistesBiblioteca.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listPistesBiblioteca);

        javax.swing.GroupLayout panelReproduccioLayout = new javax.swing.GroupLayout(panelReproduccio);
        panelReproduccio.setLayout(panelReproduccioLayout);
        panelReproduccioLayout.setHorizontalGroup(
            panelReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReproduccioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReproduccioLayout.createSequentialGroup()
                        .addComponent(comboBoxLlistes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(btnCrearLlista, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarLlista))
                    .addGroup(panelReproduccioLayout.createSequentialGroup()
                        .addGroup(panelReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addGroup(panelReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAfegirPistaLlista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarPistaLlista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReproduirLlista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReproduirSelecc, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panelReproduccioLayout.setVerticalGroup(
            panelReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReproduccioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearLlista)
                    .addComponent(btnEliminarLlista)
                    .addComponent(comboBoxLlistes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReproduccioLayout.createSequentialGroup()
                        .addComponent(btnAfegirPistaLlista)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarPistaLlista)
                        .addGap(18, 18, 18)
                        .addComponent(btnReproduirLlista)
                        .addGap(18, 18, 18)
                        .addComponent(btnReproduirSelecc))
                    .addGroup(panelReproduccioLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPanelMenu.addTab("Llistes Reproduccio", panelReproduccio);

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconPlay.png"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconPause.png"))); // NOI18N
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconStop.png"))); // NOI18N
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/PrietoDehghanPourAstor/vista/iconNext.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        chkCiclic.setText("Ciclic");
        chkCiclic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCiclicActionPerformed(evt);
            }
        });

        chkAleatori.setText("Aleatori");
        chkAleatori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAleatoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addComponent(chkCiclic, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkAleatori))
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCiclic, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAleatori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        tabbedPanelMenu.addTab("Control Reproductor", panelControl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanelMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event per a la gestio del boolea Aleatori.
     * @param evt 
     */
    private void chkAleatoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAleatoriActionPerformed
        if (chkAleatori.isSelected()) {
            control.setAleatori(true);
        } else {
            control.setAleatori(false);
        }
    }//GEN-LAST:event_chkAleatoriActionPerformed

    /**
     * Event per a passar al seguent fitxer.
     * @param evt 
     */
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            control.nextFitxer();
        } catch (FitxerAudioErrorException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * Event per a omplir la llista de pistes de reproduccio.
     * @param evt 
     */
    private void comboBoxLlistesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLlistesActionPerformed
        this.omplirPistesLlista((String) comboBoxLlistes.getSelectedItem());
    }//GEN-LAST:event_comboBoxLlistesActionPerformed

    /**
     * Event per a reproduir una llista de reproduccio.
     * @param evt 
     */
    private void btnReproduirLlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproduirLlistaActionPerformed
        try {
            control.playLlista(control.getLlistaReproduccio((String) comboBoxLlistes.getSelectedItem()));
        } catch (FitxerAudioErrorException ex) {
            System.err.println(ex.getMessage());
        } catch (CloneNotSupportedException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnReproduirLlistaActionPerformed

    /**
     * Event per a guardar en un arxiu les dades del Reproductor.
     * @param evt 
     */
    private void btnGuardarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDadesActionPerformed
        try {
            control.guardarDades("banc.dat");
        } catch (IOException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarDadesActionPerformed

    /**
     * Event per a recuperar en un arxiu les dades del Reproductor.
     * @param evt 
     */
    private void btnRecuperarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarDadesActionPerformed
        try {
            control = control.recuperarDades("banc.dat");
        } catch (IOException ex) {
            System.err.println(ex.getMessage());
        }
        this.omplirBiblioteca();
        this.omplirLlistes();
    }//GEN-LAST:event_btnRecuperarDadesActionPerformed

    /**
     * Event per a reproduir la biblioteca.
     * @param evt 
     */
    private void btnReproduirBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproduirBiblioActionPerformed
        try {
            control.playLlista();
        } catch (FitxerAudioErrorException ex) {
            System.err.println(ex.getMessage());
        } catch (CloneNotSupportedException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnReproduirBiblioActionPerformed

    /**
     * Event per a obrir el FrmAfegirFitxer.
     * @param evt 
     */
    private void btnAfegirFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirFitxerActionPerformed
        FrmAfegirFitxer fa = new FrmAfegirFitxer(this, true, control);
        fa.setVisible(true);
        
        this.omplirBiblioteca();
    }//GEN-LAST:event_btnAfegirFitxerActionPerformed

    /**
     * Event per a eliminar un fitxer de la Biblioteca.
     * @param evt 
     */
    private void btnEliminarFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFitxerActionPerformed
        if (listBiblioteca.getSelectedIndex() > -1) {
            control.eliminarFitxer(control.retornFitxer(listBiblioteca.getSelectedIndex()));
        }
        this.omplirBiblioteca();
    }//GEN-LAST:event_btnEliminarFitxerActionPerformed

    /**
     * Event per al play.
     * @param evt 
     */
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        control.resumeFitxer();
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * Event per al pause.
     * @param evt 
     */
    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        control.pauseFitxer();
    }//GEN-LAST:event_btnPauseActionPerformed

    /**
     * Event per al stop.
     * @param evt 
     */
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        control.stopFitxer();
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * Event per a gestionar el boolea Ciclic.
     * @param evt 
     */
    private void chkCiclicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCiclicActionPerformed
        if (chkCiclic.isSelected()) {
            control.setCiclic(true);
        } else {
            control.setCiclic(false);
        }
    }//GEN-LAST:event_chkCiclicActionPerformed

    /**
     * Event que obre el FrmAfegirLLista.
     * @param evt 
     */
    private void btnCrearLlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLlistaActionPerformed
        FrmAfegirLlista fal = new FrmAfegirLlista(this, true, control);
        fal.setVisible(true);
        
        this.omplirLlistes();
    }//GEN-LAST:event_btnCrearLlistaActionPerformed

    /**
     * Event per a eliminar una llista de reproduccio.
     * @param evt 
     */
    private void btnEliminarLlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLlistaActionPerformed
        control.eliminarLlistaReproduccio(control.getLlistaReproduccio((String) comboBoxLlistes.getSelectedItem()));
        
        this.omplirLlistes();
    }//GEN-LAST:event_btnEliminarLlistaActionPerformed

    /**
     * Event per a afegir un fitxer a una llista de reproduccio.
     * @param evt 
     */
    private void btnAfegirPistaLlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirPistaLlistaActionPerformed
        control.afegirFitxer(control.retornFitxer(listPistesBiblioteca.getSelectedIndex()), control.getLlistaReproduccio((String) comboBoxLlistes.getSelectedItem()));
        
        this.omplirPistesLlista((String) comboBoxLlistes.getSelectedItem());
    }//GEN-LAST:event_btnAfegirPistaLlistaActionPerformed

    /**
     * Event per a eliminar un fitxer de una llista de reproduccio.
     * @param evt 
     */
    private void btnEliminarPistaLlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPistaLlistaActionPerformed
        control.eliminarFitxer(listLlistaReproduccio.getSelectedIndex(), control.getLlistaReproduccio((String) comboBoxLlistes.getSelectedItem()));
        
        this.omplirPistesLlista((String) comboBoxLlistes.getSelectedItem());                                                  
    }//GEN-LAST:event_btnEliminarPistaLlistaActionPerformed

    /**
     * Event per a reproduir un unic arxiu de una llista de reprodducio.
     * @param evt 
     */
    private void btnReproduirSeleccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproduirSeleccActionPerformed
        control.stopFitxer();
        if (listLlistaReproduccio.getSelectedIndex() > -1) {
            try {
                control.playFitxer(listLlistaReproduccio.getSelectedIndex(), control.getLlistaReproduccio((String) comboBoxLlistes.getSelectedItem()));
            } catch (FitxerAudioErrorException ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnReproduirSeleccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReproductorUB4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirFitxer;
    private javax.swing.JButton btnAfegirPistaLlista;
    private javax.swing.JButton btnCrearLlista;
    private javax.swing.JButton btnEliminarFitxer;
    private javax.swing.JButton btnEliminarLlista;
    private javax.swing.JButton btnEliminarPistaLlista;
    private javax.swing.JButton btnGuardarDades;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRecuperarDades;
    private javax.swing.JButton btnReproduirBiblio;
    private javax.swing.JButton btnReproduirLlista;
    private javax.swing.JButton btnReproduirSelecc;
    private javax.swing.JButton btnStop;
    private javax.swing.JCheckBox chkAleatori;
    private javax.swing.JCheckBox chkCiclic;
    private javax.swing.JComboBox comboBoxLlistes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listBiblioteca;
    private javax.swing.JList listLlistaReproduccio;
    private javax.swing.JList listPistesBiblioteca;
    private javax.swing.JPanel panelBiblioteca;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelReproduccio;
    private javax.swing.JTabbedPane tabbedPanelMenu;
    // End of variables declaration//GEN-END:variables
}
